#!/usr/bin/env bash

today=$(date +%d)
day="${1-$today}"
here=$(readlink -f "${0%/*}")

[ -n "$day" ] || {
  echo >&2 "Usage: ${0##*/} day"
  exit 1
}
day=${day/day/}
target="day$day"

[ ! -d "$target" ] || {
  echo "Directory $target is already there."
  exit 0
}
echo "Setting up for day $day..."

mkdir -p "$target" || exit 1
cd "$target" || exit 1
{
  date -u
  date +%s
} > times.txt

sarg="s/dayxx/day$day/; s/day: -1/day: $day/"
sed "$sarg" "$here/skel/index.js" > index.js
chmod +x index.js
touch example.txt data.txt

# git add  example1.txt example2.txt data.txt

editor=gvim
which "$editor" >& /dev/null || editor=mvim

"$editor" -p example.txt visual.txt data.txt
"$editor" index.js

